---
- hosts: vmcloud
  remote_user: root
  tasks:
    - name: Make sure that we can connect to the machine
      ping:
    - name: Install latest version of "openjdk-8-jdk" ignoring "install-recommends"
      apt:
          name: openjdk-8-jdk
          state: latest
          install_recommends: no
    - name: Upload default jar for host
      copy: src=target/tasklist-service-1.0-SNAPSHOT.jar dest=/home/jars mode=0777
    - name: Copy service.yml file to host
      copy: src=tasklist-service.yml dest=/home/jars mode=0777
    - name: Run java app
      shell: "java -jar /home/jars/tasklist-service-1.0-SNAPSHOT.jar server /home/jars/tasklist-service.yml"
